name: Deploy MongoDB Cluster

on:
  workflow_dispatch:
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: | 
          terraform plan -var="public_key=${{ secrets.ATLAS_PUBLIC_KEY }}" \
                            -var="private_key=${{ secrets.ATLAS_PRIVATE_KEY }}" \
                            -var="project_name=${{secrets.PROJECT_NAME}}" \
                            -var="cluster_name=${{secrets.CLUSTER_NAME}}" \
                            -var="org_id=${{secrets.ORG_ID}}"
      - name: Terraform Apply
        run: | 
          terraform apply -auto-approve -var="public_key=${{ secrets.ATLAS_PUBLIC_KEY }}" \
                                           -var="private_key=${{ secrets.ATLAS_PRIVATE_KEY }}" \
                                           -var="project_name=${{secrets.PROJECT_NAME}}" \
                                           -var="cluster_name=${{secrets.CLUSTER_NAME}}" \
                                           -var="org_id=${{secrets.ORG_ID}}"